use crate::dfa::DFA;
use crate::nfa::pattern_has_until;
use crate::parser::{Definition, ModifierAst, Pattern};
use std::collections::HashMap;
use std::fmt::Write;

// ── data model ────────────────────────────────────────────────────────────────

/// What `%slice` (if present) means for a token definition.
///
/// - `None`          — no `%slice` modifier; no slice field is emitted.
/// - `Some(None)`    — `%slice` with no label; field named `slice`, whole span.
/// - `Some(Some(s))` — `%slice(label)`; field named `label`, named sub-span.
pub type SliceSpec = Option<Option<String>>;

pub struct RawC
{
	pub c_types: Vec<String>,
	pub c_funcs: Vec<String>,
}

/// A collected `%call_func(fn(arg1, arg2, ...))` modifier.
#[derive(Clone)]
pub struct CallFuncSpec
{
	pub func: String,
	pub args: Vec<String>,
}

/// Everything the generator needs to know about one token definition.
pub struct TokenDef
{
	/// Deduplicated name: the second `@comment` named "comment" → "comment_1".
	pub name: String,
	pub dfa: DFA,
	#[allow(unused)]
	pub kind: TokenKind,
	/// Named sub-span labels collected from `Until`/`Repeat` nodes.
	pub pattern_labels: Vec<String>,
	/// The `%slice` modifier, if present.
	pub slice: SliceSpec,
	/// The `%call_func(...)` modifier, if present.
	pub call_func: Option<CallFuncSpec>,
	pub ignore: bool,
	pub reserved: bool,
	/// True when the pattern contains at least one `Until` node.
	/// These tokens must use first-accept (not longest-accept) DFA simulation
	/// so that e.g. `"//" -> '\n'` stops at the very first newline, not the last.
	pub has_until: bool,
	pub custom_type: Option<String>,
}

pub enum TokenKind
{
	Keyword,
	Token,
	Literal,
	Comment,
	Ignore,
}

// ── entry point ───────────────────────────────────────────────────────────────

pub fn generate(defs: &[Definition]) -> String
{
	let errors = validate_duplicate_names(defs);
	if !errors.is_empty() {
		// surface all problems at once rather than stopping at the first
		panic!(
			"Yapper: {} validation error(s):\n{}",
			errors.len(),
			errors.iter().map(|e| format!("  - {e}")).collect::<Vec<_>>().join("\n")
		);
	}

	let token_defs = collect_token_defs(defs);
	let raw_c = collect_raw_c(defs);

	let mut out = String::new();
	writeln!(
		out,
		r#"/*
* DO NOT EDIT MANUALLY
* Generated by Yapper
* https://github.com/BloemGamer/yapper
*/"#
	)
	.unwrap();
	emit_header(&mut out);
	emit_types(&mut out, &token_defs);
	emit_raw_c_types(&mut out, &raw_c);
	emit_raw_c_funcs(&mut out, &raw_c);
	writeln!(
		out,
		r#"Token next_token(SliceString* str, size_t* offset, size_t* line, size_t* col);

#ifdef YAPPER_LEXER_IMPLEMENTATION"#
	)
	.unwrap();
	emit_tables(&mut out, &token_defs);
	emit_lexer(&mut out, &token_defs);
	writeln!(
		out,
		r#"
#endif // YAPPER_LEXER_IMPLEMENTATION"#
	)
	.unwrap();
	return out;
}

// ── pass 1: collect ───────────────────────────────────────────────────────────

fn aleady_seen(name: &str, seen: &mut HashMap<String, bool>) -> bool
{
	let already_seen = seen.entry(name.to_string()).or_insert(false);
	if !*already_seen {
		*already_seen = true;
		return false;
	} else {
		return true;
	};
}

fn collect_raw_c(defs: &[Definition]) -> RawC
{
	let mut c_types = Vec::new();
	let mut c_funcs = Vec::new();
	for def in defs {
		match def {
			Definition::CFunc { func_definition, .. } => c_funcs.push(func_definition.clone()),
			Definition::CType { type_definition, .. } => c_types.push(type_definition.clone()),
			_ => {}
		}
	}
	RawC { c_types, c_funcs }
}

fn collect_token_defs(defs: &[Definition]) -> Vec<TokenDef>
{
	let mut result = Vec::new();
	let mut seen: HashMap<String, bool> = HashMap::new();
	let mut ignore_idx: usize = 0;

	for def in defs {
		match def {
			Definition::Keyword {
				name,
				pattern,
				modifiers,
				..
			} => {
				let seen = aleady_seen(name, &mut seen);
				if !seen {
					result.push(compile_def(name, pattern, modifiers, TokenKind::Keyword));
				}
			}
			Definition::Token {
				name,
				pattern,
				modifiers,
				..
			} => {
				let seen = aleady_seen(name, &mut seen);
				if !seen {
					result.push(compile_def(name, pattern, modifiers, TokenKind::Token));
				}
			}
			Definition::Literal {
				name,
				pattern,
				modifiers,
				..
			} => {
				let seen = aleady_seen(name, &mut seen);
				if !seen {
					result.push(compile_def(name, pattern, modifiers, TokenKind::Literal));
				}
			}
			Definition::Comment {
				name,
				pattern,
				modifiers,
				..
			} => {
				let seen = aleady_seen(name, &mut seen);
				if !seen {
					result.push(compile_def(name, pattern, modifiers, TokenKind::Comment));
				}
			}
			Definition::Ignore { pattern, .. } => {
				let name = format!("ignore_{}", ignore_idx);
				ignore_idx += 1;
				let mut td = compile_def(&name, pattern, &[], TokenKind::Ignore);
				td.ignore = true;
				result.push(td);
			}
			Definition::CFunc { .. } => {}
			Definition::CType { .. } => {}
			Definition::CustomToken { name, ty, .. } => {
				let seen = aleady_seen(name, &mut seen);
				if !seen {
					result.push(TokenDef {
						name: name.clone(),
						dfa: crate::dfa::DFA {
							states: vec![],
							start: 0,
						}, // no DFA needed
						kind: TokenKind::Token,
						pattern_labels: vec![],
						slice: None,
						call_func: None,
						ignore: false,
						reserved: false,
						has_until: false,
						custom_type: ty.clone(),
					});
				}
			}
		}
	}
	result
}

fn compile_def(name: &str, pattern: &Pattern, modifiers: &[ModifierAst], kind: TokenKind) -> TokenDef
{
	let pattern_labels = collect_pattern_labels(pattern);
	let reserved = modifiers.iter().any(|m| matches!(m, ModifierAst::Reserved));
	let has_until = pattern_has_until(pattern);

	let slice: SliceSpec = modifiers.iter().find_map(|m| match m {
		ModifierAst::Slice(label) => Some(label.clone()),
		_ => None,
	});

	let call_func: Option<CallFuncSpec> = modifiers.iter().find_map(|m| match m {
		ModifierAst::CallFunc { func, args } => Some(CallFuncSpec {
			func: func.clone(),
			args: args.clone(),
		}),
		_ => None,
	});

	let dfa = {
		let nfa = crate::nfa::pattern_to_nfa(pattern);
		crate::dfa::nfa_to_dfa(&nfa)
	};

	TokenDef {
		name: name.to_string(),
		dfa,
		kind,
		pattern_labels,
		slice,
		call_func,
		ignore: false,
		reserved,
		has_until,
		custom_type: None,
	}
}

fn collect_pattern_labels(pattern: &Pattern) -> Vec<String>
{
	let mut labels = Vec::new();
	collect_pattern_labels_inner(pattern, &mut labels);
	labels
}

fn collect_pattern_labels_inner(pattern: &Pattern, out: &mut Vec<String>)
{
	match pattern {
		Pattern::Until {
			label: Some(l), end, ..
		} => {
			out.push(l.clone());
			collect_pattern_labels_inner(end, out);
		}
		Pattern::Repeat { name: Some(n), pat, .. } => {
			out.push(n.clone());
			collect_pattern_labels_inner(pat, out);
		}
		Pattern::Seq(parts, _) | Pattern::Alt(parts, _) => {
			for p in parts {
				collect_pattern_labels_inner(p, out);
			}
		}
		Pattern::Until { end, .. } => collect_pattern_labels_inner(end, out),
		Pattern::Repeat { pat, .. } => collect_pattern_labels_inner(pat, out),
		Pattern::Str(..) | Pattern::Char(..) => {}
	}
}

// ── name helpers ──────────────────────────────────────────────────────────────

fn name_to_enum_member(name: &str) -> String
{
	name.to_uppercase()
}
fn name_to_struct_member(name: &str) -> String
{
	name.to_string()
}

fn name_to_c_ident(name: &str) -> String
{
	let sanitized: String = name
		.chars()
		.map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
		.collect();
	format!("tok_{}", sanitized)
}

// ── pass 2: emit ──────────────────────────────────────────────────────────────

fn emit_header(out: &mut String)
{
	out.push_str(
		r#"#pragma once

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L
#include <stdbool.h>
#endif
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "utils/slice.h"

#ifndef SLICE_STRING_DEFINED
#define SLICE_STRING_DEFINED
DefineSliceString(String, string, char);
#endif /* SLICE_STRING_DEFINED */

/// A Span struct, that says where a token is located in a file
typedef struct Span {
	/// byte offset from the start of the source file
	size_t start;
	/// length in bytes
	size_t len;
	/// 1-based line number of the start of the token
	size_t line;
	/// 1-based column (character) number of the start of the token
	size_t col;
} Span;

"#,
	);
}

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

fn emit_types(out: &mut String, defs: &[TokenDef])
{
	// ── TokenKind enum ────────────────────────────────────────────────────────
	out.push_str(
		"/// Enum for the TokenKinds for the lexer
typedef enum TokenKind {\n",
	);
	out.push_str("\tTOKEN_KIND_INVALID = 0,\n\tTOKEN_KIND_EOF,\n");
	for def in defs {
		if def.ignore {
			continue;
		}
		if def.reserved {
			let _ = writeln!(out, "\tTOKEN_KIND_{}, /* reserved */", name_to_enum_member(&def.name));
		} else {
			let _ = writeln!(out, "\tTOKEN_KIND_{},", name_to_enum_member(&def.name));
		}
	}
	out.push_str("} TokenKind;\n\n");

	// ── Token struct ──────────────────────────────────────────────────────────
	let defs_with_slice: Vec<&TokenDef> = defs.iter().filter(|d| !d.ignore && d.slice.is_some()).collect();
	let custom_defs: Vec<&TokenDef> = defs.iter().filter(|d| !d.ignore && d.custom_type.is_some()).collect();

	out.push_str(
		"/// Struct of the token
/// @member kind -> the TokenKind of the token
/// @member span -> the Span of where the token is located in the file (start, end, line, col)
typedef struct Token {\n",
	);
	out.push_str("	TokenKind kind;\n");
	out.push_str("	/// byte offset + length in source file\n	Span span;\n");

	if !defs_with_slice.is_empty() || !custom_defs.is_empty() {
		out.push_str("	union {\n");

		for def in &defs_with_slice {
			let field_name = match &def.slice {
				Some(None) => "slice".to_string(),
				Some(Some(label)) => name_to_struct_member(label),
				None => unreachable!(),
			};
			let _ = writeln!(out, "		struct {{");
			let _ = writeln!(out, "			SliceString {};", field_name);
			let _ = writeln!(
				out,
				"		}} {}; /* TOKEN_KIND_{} */",
				name_to_struct_member(&def.name),
				name_to_enum_member(&def.name)
			);
		}

		for def in &custom_defs {
			let field_name = name_to_struct_member(&def.name);
			let ty = def.custom_type.as_deref().unwrap();
			let _ = writeln!(out, "		struct {{");
			let _ = writeln!(out, "			{} {};", ty, field_name);
			let _ = writeln!(
				out,
				"		}} {}; /* TOKEN_KIND_{} */",
				field_name,
				name_to_enum_member(&def.name)
			);
		}

		out.push_str("	} slices;\n");
	}

	out.push_str("} Token;\n\n");

	// ── token_invalid ─────────────────────────────────────────────────────────
	out.push_str("static inline Token token_invalid(void) {\n");
	out.push_str("	Token t = {};\n");
	out.push_str("	t.kind = TOKEN_KIND_INVALID;\n");
	out.push_str("	return t;\n");
	out.push_str("}\n\n");

	out.push_str("static inline Token token_eof(void) {\n");
	out.push_str("	Token t = {};\n");
	out.push_str("	t.kind = TOKEN_KIND_EOF;\n");
	out.push_str("	return t;\n");
	out.push_str("}\n\n");

	// ── token_is_reserved ────────────────────────────────────────────────────
	let reserved_defs: Vec<&TokenDef> = defs.iter().filter(|d| d.reserved).collect();
	out.push_str("static inline bool token_is_reserved(Token tok) {\n");
	if reserved_defs.is_empty() {
		out.push_str("	(void)tok;\n	return false;\n");
	} else {
		out.push_str("	switch (tok.kind) {\n");
		for def in &reserved_defs {
			let _ = writeln!(
				out,
				"		case TOKEN_KIND_{}: return true;",
				name_to_enum_member(&def.name)
			);
		}
		out.push_str("		default: return false;\n	}\n");
	}
	out.push_str("}\n\n");

	// ── token_kind_name ───────────────────────────────────────────────────────
	out.push_str("static inline const char* token_kind_name(TokenKind kind) {\n");
	out.push_str("	switch (kind) {\n");
	out.push_str("		case TOKEN_KIND_INVALID: return \"INVALID\";\n");
	for def in defs {
		if def.ignore {
			continue;
		}
		let _ = writeln!(
			out,
			"		case TOKEN_KIND_{0}: return \"{0}\";",
			name_to_enum_member(&def.name)
		);
	}
	out.push_str("		default: return \"<unknown>\";\n    }\n");
	out.push_str("}\n\n");

	// ── token_print ───────────────────────────────────────────────────────────
	out.push_str(
		r#"static inline void token_print(const char* src, Token tok) {
	printf("%s[%zu:%zu] \"%.*s\"\n",
		token_kind_name(tok.kind),
		tok.span.line,
		tok.span.col,
		(int)tok.span.len,
		src + tok.span.start
	);
}

"#,
	);

	emit_call_func_forward_decls(out, defs);
}

fn emit_call_func_forward_decls(out: &mut String, defs: &[TokenDef])
{
	for def in defs {
		let cf = match &def.call_func {
			Some(cf) => cf,
			None => continue,
		};

		let _ = writeln!(
			out,
			"/* forward declaration for TOKEN_KIND_{} */",
			name_to_enum_member(&def.name)
		);

		let mut params = vec!["SliceString* str".to_string()];
		for arg in &cf.args {
			params.push(format!("SliceString {}", arg));
		}
		let params_str = params.join(", ");

		let _ = writeln!(out, "Token {}({});\n", cf.func, params_str);
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// DFA tables
// ─────────────────────────────────────────────────────────────────────────────

fn emit_tables(out: &mut String, defs: &[TokenDef])
{
	for def in defs {
		let dfa = &def.dfa;
		let n = dfa.states.len();
		if n == 0 {
			continue;
		}
		let pfx = name_to_c_ident(&def.name);

		let _ = writeln!(out, "/* DFA tables for '{}' ({} states) */", def.name, n);

		// ── transition table [state][byte] ────────────────────────────────────
		let _ = writeln!(out, "static const int {pfx}_trans[{n}][256] = {{");
		for (sid, state) in dfa.states.iter().enumerate() {
			let mut row = [-1i32; 256];
			for (&c, &next) in &state.transitions {
				if (c as u32) < 256 {
					row[c as usize] = next as i32;
				}
			}
			out.push_str("	{");
			for chunk in row.chunks(16) {
				out.push_str("\n\t\t");
				for (i, &v) in chunk.iter().enumerate() {
					if i > 0 {
						out.push_str(", ");
					}
					let _ = write!(out, "{:3}", v);
				}
				out.push(',');
			}
			let _ = writeln!(out, "\n	}}, /* state {} */", sid);
		}
		out.push_str("};\n\n");

		// ── any-transition table [state] ──────────────────────────────────────
		let _ = writeln!(out, "static const int {pfx}_any[{n}] = {{");
		out.push('\t');
		for (i, state) in dfa.states.iter().enumerate() {
			if i > 0 {
				out.push_str(", ");
			}
			match state.any_transition {
				Some(s) => {
					let _ = write!(out, "{:3}", s as i32);
				}
				None => out.push_str(" -1"),
			}
		}
		out.push_str("\n};\n\n");

		// ── accept table [state] ──────────────────────────────────────────────
		let _ = writeln!(out, "static const int {pfx}_accept[{n}] = {{");
		out.push('\t');
		for (i, state) in dfa.states.iter().enumerate() {
			if i > 0 {
				out.push_str(", ");
			}
			out.push_str(if state.is_accept { "  1" } else { "  0" });
		}
		out.push_str("\n};\n\n");
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Lexer functions
// ─────────────────────────────────────────────────────────────────────────────

fn emit_lexer(out: &mut String, defs: &[TokenDef])
{
	emit_dfa_run(out);
	emit_next_token(out, defs);
}

fn emit_dfa_run(out: &mut String)
{
	out.push_str(
		r#"/** --------------------------------------------------------------------------
 * @brief dfa_run — generic DFA simulation
 *
 * Runs the DFA described by (trans, any, accept) over (input, len).
 * Returns the length in bytes of the longest accepting prefix, or -1.
 *
 * Priority: concrete char transition > any-transition > dead (stop).
 *
 * UTF-8: continuation bytes (10xxxxxx) are skipped after each codepoint so
 * that a wildcard (any) transition counts as one logical character, not one
 * byte.  ASCII-only patterns are unaffected.
 *
 * first_accept: when non-zero the simulation stops as soon as an accepting
 * state is reached, rather than continuing to find the longest match.
 * Use this for `Until`-based tokens (e.g. `"//" -> '\n'`) so that the
 * terminator is not consumed as body text by a longer match.
 * --------------------------------------------------------------------------*/
static ptrdiff_t dfa_run(
	const char*  input,
	size_t       len,
	const int    trans[][256],
	const int*   any,
	const int*   accept,
	int          n_states,
	int          start,
	int          first_accept)
{
	(void)n_states;
	int       state       = start;
	ptrdiff_t last_accept = -1;

	for (size_t i = 0; i < len; ) {
		unsigned char byte = (unsigned char)input[i];

		int next = trans[state][byte];
		if (next < 0) {
			next = any[state]; /* wildcard fallback */
		}
		if (next < 0) {
			break; /* dead state */
		}

		state = next;
		i++;
		/* skip UTF-8 continuation bytes */
		while (i < len && ((unsigned char)input[i] & 0xC0u) == 0x80u) {
			i++;
		}

		if (accept[state]) {
			last_accept = (ptrdiff_t)i;
			if (first_accept) {
				break; /* stop at first match — don't extend past the terminator */
			}
		}
	}

	return last_accept;
}

"#,
	);
}

fn emit_next_token(out: &mut String, defs: &[TokenDef])
{
	let normal_defs: Vec<&TokenDef> = defs.iter().filter(|d| !d.ignore && d.custom_type.is_none()).collect();
	let ignore_defs: Vec<&TokenDef> = defs.iter().filter(|d| d.ignore).collect();

	out.push_str(
		r#"/** --------------------------------------------------------------------------
 * @brief next_token — consume one token from the front of str.
 *
 * str    — remaining source text (passed by value; caller must advance it)
 * offset — absolute byte offset of str.data from the start of the file
 * line   — current 1-based line number (updated in place)
 * col    — current 1-based column number (updated in place)
 *
 * Definitions with %call_func delegate token construction entirely to the
 * user function: next_token calls fn(str, args...) and returns its result.
 * The user function is responsible for filling in tok.span.
 *
 * Definitions without %call_func have their Token built here automatically.
 *
 * Custom tokens (@custom_token) are never produced by the lexer automatically;
 * they are emitted only by user code via %call_func.
 *
 * Returns TOKEN_KIND_INVALID when str is empty or no rule matched.
 * --------------------------------------------------------------------------*/
Token next_token(SliceString* str, size_t* offset, size_t* line, size_t* col)
{
	for (;;) {
		if (str->len == 0) {
			return token_eof();
		}

		const char* src = str->data;
		size_t      rem = str->len;

		ptrdiff_t best_len       = -1;
		int       best_kind      = TOKEN_KIND_INVALID;
		int       best_is_ignore = 0;

"#,
	);

	for def in &normal_defs {
		let n = def.dfa.states.len();
		let pfx = name_to_c_ident(&def.name);
		let kind_enum = format!("TOKEN_KIND_{}", name_to_enum_member(&def.name));
		let first_accept = if def.has_until { 1 } else { 0 };

		let _ = writeln!(out, "		/* --- {} --- */", def.name);
		let _ = writeln!(
			out,
			"		{{\n\
             \t\t\tptrdiff_t m = dfa_run(src, rem, {pfx}_trans, {pfx}_any, {pfx}_accept, {n}, 0, {first_accept});\n\
             \t\t\tif (m > best_len) {{ best_len = m; best_kind = {kind_enum}; best_is_ignore = 0; }}\n\
             \t\t}}"
		);
	}

	for def in &ignore_defs {
		let n = def.dfa.states.len();
		let pfx = name_to_c_ident(&def.name);
		let first_accept = if def.has_until { 1 } else { 0 };

		let _ = writeln!(out, "		/* --- @ignore: {} --- */", def.name);
		let _ = writeln!(
			out,
			"		{{\n\
             \t\t\tptrdiff_t m = dfa_run(src, rem, {pfx}_trans, {pfx}_any, {pfx}_accept, {n}, 0, {first_accept});\n\
             \t\t\tif (m > best_len) {{ best_len = m; best_kind = 0; best_is_ignore = 1; }}\n\
             \t\t}}"
		);
	}

	out.push_str(
		r#"
		if (best_len <= 0) {
			Token tok = token_invalid();
			tok.span.start = *offset;
			tok.span.len   = 0;
			tok.span.line  = *line;
			tok.span.col   = *col;
			return tok;
		}

		/* advance the input past the match */
		str->data += best_len;
		str->len  -= (size_t)best_len;
		*offset   += (size_t)best_len;

		if (best_is_ignore) {
			for (ptrdiff_t i = 0; i < best_len; i++) {
				if (src[i] == '\n') { (*line)++; *col = 1; }
				else                { (*col)++; }
			}
			continue;
		}

		switch ((TokenKind)best_kind) {
"#,
	);

	for def in &normal_defs {
		let kind_enum = format!("TOKEN_KIND_{}", name_to_enum_member(&def.name));

		match &def.call_func {
			Some(cf) => {
				let mut call_args = vec!["str".to_string()];
				for arg in &cf.args {
					let is_slice_field = match &def.slice {
						Some(None) => arg == "slice",
						Some(Some(l)) => arg == l,
						None => false,
					};
					#[allow(clippy::if_same_then_else)]
					if is_slice_field || def.pattern_labels.contains(arg) {
						call_args.push("matched".to_string());
					} else {
						call_args.push("matched".to_string());
					}
				}

				let needs_matched = !cf.args.is_empty();
				let matched_decl = if needs_matched {
					"\t\t\tSliceString matched = { .data = (char*)src, .len = (size_t)best_len };\n"
				} else {
					""
				};

				let call_str = format!("{}({})", cf.func, call_args.join(", "));
				let _ = writeln!(
					out,
					"		case {kind_enum}: {{\n\
                     {matched_decl}\
                     \t\t\tconst char* call_start = str->data;\n\
                     \t\t\tToken tok = {call_str};\n\
                     \t\t\tsize_t extra = (size_t)(str->data - call_start);\n\
                     \t\t\tsize_t total = (size_t)best_len + extra;\n\
                     \t\t\t*offset        += extra;\n\
                     \t\t\ttok.span.start  = *offset - total;\n\
                     \t\t\ttok.span.len    = total;\n\
                     \t\t\ttok.span.line   = *line;\n\
                     \t\t\ttok.span.col    = *col;\n\
                     \t\t\tfor (size_t i = 0; i < total; i++) {{\n\
                     \t\t\t\tif (src[i] == '\\n') {{ (*line)++; *col = 1; }}\n\
                     \t\t\t\telse                {{ (*col)++; }}\n\
                     \t\t\t}}\n\
                     \t\t\treturn tok;\n\
                     \t\t}}"
				);
			}
			None => {
				let _ = writeln!(
					out,
					"		case {kind_enum}: {{\n\
                     \t\t\tToken tok;\n\
                     \t\t\tmemset(&tok, 0, sizeof(tok));\n\
                     \t\t\ttok.kind       = {kind_enum};\n\
                     \t\t\ttok.span.start = *offset - (size_t)best_len;\n\
                     \t\t\ttok.span.len   = (size_t)best_len;\n\
                     \t\t\ttok.span.line  = *line;\n\
                     \t\t\ttok.span.col   = *col;\n\
                     \t\t\tfor (ptrdiff_t i = 0; i < best_len; i++) {{\n\
                     \t\t\t\tif (src[i] == '\\n') {{ (*line)++; *col = 1; }}\n\
                     \t\t\t\telse                {{ (*col)++; }}\n\
                     \t\t\t}}\n\
                     \t\t\treturn tok;\n\
                     \t\t}}"
				);
			}
		}
	}

	out.push_str(
		r#"		default: {token_invalid();
			Token tok = token_invalid();
			tok.span.start = *offset;
			tok.span.len   = 0;
			tok.span.line  = *line;
			tok.span.col   = *col;
			return tok;};
		}
	}
}

"#,
	);
}

fn emit_raw_c_types(out: &mut String, raw_c: &RawC)
{
	for ty in &raw_c.c_types {
		out.push_str(ty);
		out.push_str("\n\n");
	}
}

fn emit_raw_c_funcs(out: &mut String, raw_c: &RawC)
{
	for func in &raw_c.c_funcs {
		out.push_str(func);
		out.push_str("\n\n");
	}
}

// ── validation helpers ────────────────────────────────────────────────────────

fn token_kind_label(def: &Definition) -> &'static str
{
	match def {
		Definition::Keyword { .. } => "keyword",
		Definition::Token { .. } => "token",
		Definition::Literal { .. } => "literal",
		Definition::Comment { .. } => "comment",
		Definition::Ignore { .. } => "ignore",
		Definition::CFunc { .. } => "cfunc",
		Definition::CType { .. } => "ctype",
		Definition::CustomToken { .. } => "custom_token",
	}
}

fn slice_shape_label(modifiers: &[ModifierAst]) -> String
{
	match modifiers.iter().find_map(|m| match m {
		ModifierAst::Slice(label) => Some(label.clone()),
		_ => None,
	}) {
		None => "no_slice".to_string(),
		Some(None) => "slice(unnamed)".to_string(),
		Some(Some(l)) => format!("slice({})", l),
	}
}

/// Validate that all definitions sharing the same name agree on:
///   1. definition kind  (keyword / token / literal / comment / …)
///   2. slice shape      (no slice / unnamed slice / named slice "foo")
///
/// Returns a list of human-readable error messages (empty = all good).
pub fn validate_duplicate_names(defs: &[Definition]) -> Vec<String>
{
	// name → (kind_label, slice_shape, first_occurrence_index)
	let mut seen: HashMap<&str, (&'static str, String, usize)> = HashMap::new();
	let mut errors: Vec<String> = Vec::new();

	for (i, def) in defs.iter().enumerate() {
		let name = match def {
			Definition::Keyword { name, .. }
			| Definition::Token { name, .. }
			| Definition::Literal { name, .. }
			| Definition::Comment { name, .. }
			| Definition::CustomToken { name, .. } => name.as_str(),
			// Ignore / CFunc / CType have no user-visible name — skip
			_ => continue,
		};

		let kind = token_kind_label(def);
		let shape = match def {
			Definition::Keyword { modifiers, .. }
			| Definition::Token { modifiers, .. }
			| Definition::Literal { modifiers, .. }
			| Definition::Comment { modifiers, .. } => slice_shape_label(modifiers),
			Definition::CustomToken { ty, .. } => format!("custom_type({})", ty.as_deref().unwrap_or("?")),
			_ => "no_slice".to_string(),
		};

		match seen.get(name) {
			None => {
				seen.insert(name, (kind, shape, i));
			}
			Some((prev_kind, prev_shape, prev_i)) => {
				if *prev_kind != kind {
					errors.push(format!(
						"duplicate name '{}': definition #{} is a {} but definition #{} is a {}",
						name,
						prev_i + 1,
						prev_kind,
						i + 1,
						kind
					));
				}
				if prev_shape != &shape {
					errors.push(format!(
						"duplicate name '{}': definition #{} has output '{}' but definition #{} has '{}'",
						name,
						prev_i + 1,
						prev_shape,
						i + 1,
						shape
					));
				}
			}
		}
	}

	errors
}
